### ISSUE TITLE
Left and Right mousebutton navigation in 3D panel does not work.

### ISSUE THREAD

**Issue by moongaze** [animanathome/movemebugs#10]
Selecting and moving control objects always works in 3D panel.
Zooming works too, unless left or right mouse button was click+dragged. Then zooming fails.
Just clicking does not break anything.
After clicking in another panel, zooming in 3D panel is again possible.

In the key panel, rightmouse(panning) works, as does selecting and click dragging with MMB to zoom horizontally or vertically.

Tested on Win7 pro desktop and Win7 home laptop in Firefox 39.0 and Chrome Version 43.0.2357.134 m
Desktop has wacom+extra USB mouse, Laptop has touchpad + bluetooth mouse.

**Comment by animanathome** [comment]
Hi moongaze, thanks for submitting an issue. I'm not sure what your expectation is in terms of camera/viewport interaction. I've just released a new version which tries to match what maya has. It is what most people seem to be requesting so far. I guess it's since that's what they are used to. Please give that a try and let me know if you still find the same issues. Thanks.

**Comment by animanathome** [comment]
I'll also make sure I add the new shortcuts somewhere. Maybe a dedicated page?

**Comment by animanathome** [comment]
Hi @moongaze, can I close this issue?

**Comment by moongaze** [comment]
Sure! 

Date: Thu, 16 Jul 2015 22:06:17 -0700
